//Page 10
//Sample Program Using Math Function
//1.4 Simple program 2:Adding two Numbers
//Header File
/*NAME
stdio.h - standard buffered input/output
 SYNOPSIS


#include <stdio.h>

 DESCRIPTION
The <stdio.h> header defines the following macro names as positive integral constant expressions:
BUFSIZ
Size of <stdio.h> buffers.
FILENAME_MAX
Maximum size in bytes of the longest filename string that the implementation guarantees can be opened.
FOPEN_MAX
Number of streams which the implementation guarantees can be open simultaneously. The value will be at least eight.
_IOFBF
Input/output fully buffered.
_IOLBF
Input/output line buffered.
_IONBF
Input/output unbuffered.
L_ctermid
Maximum size of character array to hold ctermid() output.
L_cuserid
Maximum size of character array to hold cuserid() output. (LEGACY)
L_tmpnam
Maximum size of character array to hold tmpnam() output.
SEEK_CUR
Seek relative to current position.
SEEK_END
Seek relative to end-of-file.
SEEK_SET
Seek relative to start-of-file.
TMP_MAX
Minimum number of unique filenames generated by tmpnam(). Maximum number of times an application can call tmpnam() reliably. The value of TMP_MAX will be at least 10,000.
The following macro name is defined as a negative integral constant expression:

EOF
End-of-file return value.
The following macro name is defined as a null pointer constant:

NULL
Null pointer.
The following macro name is defined as a string constant:

P_tmpdir
default directory prefix for tempnam().
The following macro names are defined as expressions of type pointer to FILE:

stderr
Standard error output stream.
stdin
Standard input stream.
stdout
Standard output stream.
The following data types are defined through typedef:

FILE
A structure containing information about a file.
fpos_t
Type containing all information needed to specify uniquely every position within a file.
va_list
As described in <stdarg.h>.
size_t
As described in <stddef.h>.
The following are declared as functions and may also be defined as macros. Function prototypes must be provided for use with an ISO C compiler.


void     clearerr(FILE *);
char    *ctermid(char *);
char    *cuserid(char *);(LEGACY)
int      fclose(FILE *);
FILE    *fdopen(int, const char *);
int      feof(FILE *);
int      ferror(FILE *);
int      fflush(FILE *);
int      fgetc(FILE *);
int      fgetpos(FILE *, fpos_t *);
char    *fgets(char *, int, FILE *);
int      fileno(FILE *);
void     flockfile(FILE *);
FILE    *fopen(const char *, const char *);
int      fprintf(FILE *, const char *, ...);
int      fputc(int, FILE *);
int      fputs(const char *, FILE *);
size_t   fread(void *, size_t, size_t, FILE *);
FILE    *freopen(const char *, const char *, FILE *);
int      fscanf(FILE *, const char *, ...);
int      fseek(FILE *, long int, int);
int      fseeko(FILE *, off_t, int);
int      fsetpos(FILE *, const fpos_t *);
long int ftell(FILE *);
off_t    ftello(FILE *);
int      ftrylockfile(FILE *);
void     funlockfile(FILE *);
size_t   fwrite(const void *, size_t, size_t, FILE *);
int      getc(FILE *);
int      getchar(void);
int      getc_unlocked(FILE *);
int      getchar_unlocked(void);
int      getopt(int, char * const[], const char); (LEGACY)
char    *gets(char *);
int      getw(FILE *);
int      pclose(FILE *);
void     perror(const char *);
FILE    *popen(const char *, const char *);
int      printf(const char *, ...);
int      putc(int, FILE *);
int      putchar(int);
int      putc_unlocked(int, FILE *);
int      putchar_unlocked(int);
int      puts(const char *);
int      putw(int, FILE *);
int      remove(const char *);
int      rename(const char *, const char *);
void     rewind(FILE *);
int      scanf(const char *, ...);
void     setbuf(FILE *, char *);
int      setvbuf(FILE *, char *, int, size_t);
int      snprintf(char *, size_t, const char *, ...);
int      sprintf(char *, const char *, ...);
int      sscanf(const char *, const char *, int ...);
char    *tempnam(const char *, const char *);
FILE    *tmpfile(void);
char    *tmpnam(char *);
int      ungetc(int, FILE *);
int      vfprintf(FILE *, const char *, va_list);
int      vprintf(const char *, va_list);
int      vsnprintf(char *, size_t, const char *, va_list);
int      vsprintf(char *, const char *, va_list);

The following external variables are defined:


extern char  *optarg;    )
extern int    opterr;    )
extern int    optind;    ) (LEGACY)
extern int    optopt;    )

Inclusion of the <stdio.h> header may also make visible all symbols from <stddef.h>. */




/*
 NAME
math.h - mathematical declarations
 SYNOPSIS


#include <math.h>

 DESCRIPTION
The <math.h> header provides for the following constants. The values are of type double and are accurate within the precision of the double type.
M_E
Value of e
M_LOG2E
Value of log2e
M_LOG10E
Value of log10e
M_LN2
Value of loge2
M_LN10
Value of loge10
M_PI
Value of
M_PI_2
Value of /2
M_PI_4
Value of /4
M_1_PI
Value of 1/
M_2_PI
Value of 2/
M_2_SQRTPI
Value of 2/
M_SQRT2
Value of 2
M_SQRT1_2
Value of 1/2
The header defines the following symbolic constants:

MAXFLOAT
Value of maximum non-infinite single-precision floating point number.
HUGE_VAL
A positive double expression, not necessarily representable as a float. Used as an error value returned by the mathematics library. HUGE_VAL evaluates to positive infinity on systems supporting the ANSI/IEEE Std 754:1985 standard.
The following are declared as functions and may also be defined as macros. Function prototypes must be provided for use with an ISO C compiler.


double acos(double);
double asin(double);
double atan(double);
double atan2(double, double);
double ceil(double);
double cos(double);
double cosh(double);
double exp(double);
double fabs(double);
double floor(double);
double fmod(double, double);
double frexp(double, int *);
double ldexp(double, int);
double log(double);
double log10(double);
double modf(double, double *);
double pow(double, double);
double sin(double);
double sinh(double);
double sqrt(double);
double tan(double);
double tanh(double);
double erf(double);
double erfc(double);
double gamma(double);
double hypot(double, double);
double j0(double);
double j1(double);
double jn(int, double);
double lgamma(double);
double y0(double);
double y1(double);
double yn(int, double);
int    isnan(double);
double acosh(double);
double asinh(double);
double atanh(double);
double cbrt(double);
double expm1(double);
int    ilogb(double);
double log1p(double);
double logb(double);
double nextafter(double, double);
double remainder(double, double);
double rint(double);
double scalb(double, double);

The following external variable is defined:


extern int signgam;

 APPLICATION USAGE
None.
 FUTURE DIRECTIONS
None.
*/






#include<stdio.h>
#include<math.h>
//Symbolic Constant
#define PI 3.1416
#define MAX 180

//Main function begin
int main(void)
{
    int angle;
    float x, y;
    angle = 0;
    printf("          Angle        Cos(angle)\n\n");
    while(angle <= MAX)
    {
        //Math M_PI Constant in math.h header file
        x = (M_PI/MAX)*angle; //If you want you can use symbolic constant PI x = (PI/MAX)*angle;
        y = cos(x);
        printf("%15d %13.4f\n", angle, y);
        angle += 10;
    }//loop end
}
//Main function end
//OutPut
/*
          Angle        Cos(angle)

              0        1.0000
             10        0.9848
             20        0.9397
             30        0.8660
             40        0.7660
             50        0.6428
             60        0.5000
             70        0.3420
             80        0.1736
             90       -0.0000
            100       -0.1736
            110       -0.3420
            120       -0.5000
            130       -0.6428
            140       -0.7660
            150       -0.8660
            160       -0.9397
            170       -0.9848
            180       -1.0000

Process returned 0 (0x0)   execution time : 0.062 s
Press any key to continue.
*/
